runtime: nodejs
env: flex

env_variables:
  MYSQL_USER: jamal
  MYSQL_PASSWORD: "jamal123"
  MYSQL_DATABASE: mydemodb
  MYSQL_SOCKET_PATH: /cloudsql/plated-campaign-247606:us-central1:demodb

beta_settings:
  cloud_sql_instances: plated-campaign-247606:us-central1:demodb
